version: '3.8'

services:
  database:
    container_name: mysql_database
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - rabit_exam_network
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/

  application:
    container_name: application
    build: .
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    networks:
      - rabit_exam_network

networks:
  rabit_exam_network:
    driver: bridge